FORMAT: 1A
HOST: https://qa1.google.co.uk/api

# Flags/{:patient_id}

description blah blah blah

## Flags/{:patient_id} collection [/flags/{:patient_id}]

### Flags/{:patient_id} Index [GET]

+ Response 200 application/json

        [
          {
            "id": 4,
            "patient_id": 783,
            "description": "this patient is a pest",
            "created_by_id": 631,
            "updated_by_id": 631,
            "created_at": "2016-06-14T10:50:10.000+01:00",
            "updated_at": "2016-06-14T10:50:10.000+01:00",
            "updated_by_name": "Seymour Butts 631",
            "created_by_name": "Seymour Butts 631"
          },
          {
            "id": 5,
            "patient_id": 783,
            "description": "this patient is a pest",
            "created_by_id": 632,
            "updated_by_id": 632,
            "created_at": "2016-06-14T10:50:10.000+01:00",
            "updated_at": "2016-06-14T10:50:10.000+01:00",
            "updated_by_name": "Seymour Butts 632",
            "created_by_name": "Seymour Butts 632"
          },
          {
            "id": 6,
            "patient_id": 783,
            "description": "this patient is a pest",
            "created_by_id": 633,
            "updated_by_id": 633,
            "created_at": "2016-06-14T10:50:10.000+01:00",
            "updated_at": "2016-06-14T10:50:10.000+01:00",
            "updated_by_name": "Seymour Butts 633",
            "created_by_name": "Seymour Butts 633"
          }
        ]

## Flags/{:patient_id} collection [/flags/{:patient_id}]

### Flags/{:patient_id} Index [GET]

+ Response 200 application/json

        [
          {
            "id": 7,
            "patient_id": 785,
            "description": "this patient is a pest",
            "created_by_id": 639,
            "updated_by_id": 639,
            "created_at": "2016-06-14T10:50:11.000+01:00",
            "updated_at": "2016-06-14T10:50:11.000+01:00",
            "updated_by_name": "Seymour Butts 639",
            "created_by_name": "Seymour Butts 639"
          },
          {
            "id": 8,
            "patient_id": 785,
            "description": "this patient is a pest",
            "created_by_id": 640,
            "updated_by_id": 640,
            "created_at": "2016-06-14T10:50:11.000+01:00",
            "updated_at": "2016-06-14T10:50:11.000+01:00",
            "updated_by_name": "Seymour Butts 640",
            "created_by_name": "Seymour Butts 640"
          },
          {
            "id": 9,
            "patient_id": 785,
            "description": "this patient is a pest",
            "created_by_id": 641,
            "updated_by_id": 641,
            "created_at": "2016-06-14T10:50:11.000+01:00",
            "updated_at": "2016-06-14T10:50:11.000+01:00",
            "updated_by_name": "Seymour Butts 641",
            "created_by_name": "Seymour Butts 641"
          }
        ]

## Flags/{:patient_id} collection [/flags/{:patient_id}]

### Flags/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "description": "this is a test"
        }

+ Response 201 application/json

        {
          "id": 10,
          "patient_id": 786,
          "description": "this is a test",
          "created_by_id": 642,
          "updated_by_id": 642,
          "created_at": "2016-06-14T10:50:11.468+01:00",
          "updated_at": "2016-06-14T10:50:11.468+01:00",
          "updated_by_name": "Seymour Butts 1",
          "created_by_name": "Seymour Butts 1"
        }

## Flags/{:patient_id} collection [/flags/{:patient_id}]

### Flags/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "description": "this is a test"
        }

+ Response 201 application/json

        {
          "id": 11,
          "patient_id": 787,
          "description": "this is a test",
          "created_by_id": 643,
          "updated_by_id": 643,
          "created_at": "2016-06-14T10:50:11.629+01:00",
          "updated_at": "2016-06-14T10:50:11.629+01:00",
          "updated_by_name": "Seymour Butts 1",
          "created_by_name": "Seymour Butts 1"
        }

## Flags/{:id} collection [/flags/{:id}]

### Flags/{:id} Show [GET]

+ Response 200 application/json

        {
          "id": 12,
          "patient_id": 788,
          "description": "This patient is a pest",
          "created_by_id": 645,
          "updated_by_id": 645,
          "created_at": "2016-06-14T10:50:11.000+01:00",
          "updated_at": "2016-06-14T10:50:11.000+01:00",
          "updated_by_name": "Seymour Butts 645",
          "created_by_name": "Seymour Butts 645"
        }

## Flags/{:id} collection [/flags/{:id}]

### Flags/{:id} Update [PATCH]

+ Request 

    + Body

        {
          "description": "changed desc"
        }

+ Response 200 application/json

        {
          "id": 13,
          "patient_id": 789,
          "description": "changed desc",
          "created_by_id": 647,
          "updated_by_id": 646,
          "created_at": "2016-06-14T10:50:11.000+01:00",
          "updated_at": "2016-06-14T10:50:11.941+01:00",
          "updated_by_name": "Seymour Butts 1",
          "created_by_name": "Seymour Butts 647"
        }

## Flags/{:id} collection [/flags/{:id}]

### Flags/{:id} Destroy [DELETE]

+ Response 200 application/json

        {
          "id": 14,
          "patient_id": 790,
          "description": "This patient is a pest",
          "created_by_id": 649,
          "updated_by_id": 649,
          "created_at": "2016-06-14T10:50:12.000+01:00",
          "updated_at": "2016-06-14T10:50:12.097+01:00",
          "updated_by_name": "Seymour Butts 649",
          "created_by_name": "Seymour Butts 649"
        }

## Flags/{:patient_id} collection [/flags/{:patient_id}]

### Flags/{:patient_id} Index [GET]

+ Response 200 application/json

        [
          {
            "id": 4,
            "patient_id": 783,
            "description": "this patient is a pest",
            "created_by_id": 631,
            "updated_by_id": 631,
            "created_at": "2016-06-14T11:01:29.000+01:00",
            "updated_at": "2016-06-14T11:01:29.000+01:00",
            "updated_by_name": "Seymour Butts 631",
            "created_by_name": "Seymour Butts 631"
          },
          {
            "id": 5,
            "patient_id": 783,
            "description": "this patient is a pest",
            "created_by_id": 632,
            "updated_by_id": 632,
            "created_at": "2016-06-14T11:01:29.000+01:00",
            "updated_at": "2016-06-14T11:01:29.000+01:00",
            "updated_by_name": "Seymour Butts 632",
            "created_by_name": "Seymour Butts 632"
          },
          {
            "id": 6,
            "patient_id": 783,
            "description": "this patient is a pest",
            "created_by_id": 633,
            "updated_by_id": 633,
            "created_at": "2016-06-14T11:01:29.000+01:00",
            "updated_at": "2016-06-14T11:01:29.000+01:00",
            "updated_by_name": "Seymour Butts 633",
            "created_by_name": "Seymour Butts 633"
          }
        ]

## Flags/{:patient_id} collection [/flags/{:patient_id}]

### Flags/{:patient_id} Index [GET]

+ Response 200 application/json

        [
          {
            "id": 7,
            "patient_id": 785,
            "description": "this patient is a pest",
            "created_by_id": 639,
            "updated_by_id": 639,
            "created_at": "2016-06-14T11:01:29.000+01:00",
            "updated_at": "2016-06-14T11:01:29.000+01:00",
            "updated_by_name": "Seymour Butts 639",
            "created_by_name": "Seymour Butts 639"
          },
          {
            "id": 8,
            "patient_id": 785,
            "description": "this patient is a pest",
            "created_by_id": 640,
            "updated_by_id": 640,
            "created_at": "2016-06-14T11:01:29.000+01:00",
            "updated_at": "2016-06-14T11:01:29.000+01:00",
            "updated_by_name": "Seymour Butts 640",
            "created_by_name": "Seymour Butts 640"
          },
          {
            "id": 9,
            "patient_id": 785,
            "description": "this patient is a pest",
            "created_by_id": 641,
            "updated_by_id": 641,
            "created_at": "2016-06-14T11:01:29.000+01:00",
            "updated_at": "2016-06-14T11:01:29.000+01:00",
            "updated_by_name": "Seymour Butts 641",
            "created_by_name": "Seymour Butts 641"
          }
        ]

## Flags/{:patient_id} collection [/flags/{:patient_id}]

### Flags/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "description": "this is a test"
        }

+ Response 201 application/json

        {
          "id": 10,
          "patient_id": 786,
          "description": "this is a test",
          "created_by_id": 642,
          "updated_by_id": 642,
          "created_at": "2016-06-14T11:01:30.187+01:00",
          "updated_at": "2016-06-14T11:01:30.187+01:00",
          "updated_by_name": "Seymour Butts 1",
          "created_by_name": "Seymour Butts 1"
        }

## Flags/{:patient_id} collection [/flags/{:patient_id}]

### Flags/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "description": "this is a test"
        }

+ Response 201 application/json

        {
          "id": 11,
          "patient_id": 787,
          "description": "this is a test",
          "created_by_id": 643,
          "updated_by_id": 643,
          "created_at": "2016-06-14T11:01:30.336+01:00",
          "updated_at": "2016-06-14T11:01:30.336+01:00",
          "updated_by_name": "Seymour Butts 1",
          "created_by_name": "Seymour Butts 1"
        }

## Flags/{:id} collection [/flags/{:id}]

### Flags/{:id} Show [GET]

+ Response 200 application/json

        {
          "id": 12,
          "patient_id": 788,
          "description": "This patient is a pest",
          "created_by_id": 645,
          "updated_by_id": 645,
          "created_at": "2016-06-14T11:01:30.000+01:00",
          "updated_at": "2016-06-14T11:01:30.000+01:00",
          "updated_by_name": "Seymour Butts 645",
          "created_by_name": "Seymour Butts 645"
        }

## Flags/{:id} collection [/flags/{:id}]

### Flags/{:id} Update [PATCH]

+ Request 

    + Body

        {
          "description": "changed desc"
        }

+ Response 200 application/json

        {
          "id": 13,
          "patient_id": 789,
          "description": "changed desc",
          "created_by_id": 647,
          "updated_by_id": 646,
          "created_at": "2016-06-14T11:01:30.000+01:00",
          "updated_at": "2016-06-14T11:01:30.659+01:00",
          "updated_by_name": "Seymour Butts 1",
          "created_by_name": "Seymour Butts 647"
        }

## Flags/{:id} collection [/flags/{:id}]

### Flags/{:id} Destroy [DELETE]

+ Response 200 application/json

        {
          "id": 14,
          "patient_id": 790,
          "description": "This patient is a pest",
          "created_by_id": 649,
          "updated_by_id": 649,
          "created_at": "2016-06-14T11:01:30.000+01:00",
          "updated_at": "2016-06-14T11:01:30.819+01:00",
          "updated_by_name": "Seymour Butts 649",
          "created_by_name": "Seymour Butts 649"
        }

## Flags/{:patient_id} collection [/flags/{:patient_id}]

### Flags/{:patient_id} Index [GET]

+ Response 200 application/json

        [
          {
            "id": 4,
            "patient_id": 820,
            "description": "this patient is a pest",
            "created_by_id": 650,
            "updated_by_id": 650,
            "created_at": "2016-06-16T10:27:19.000+01:00",
            "updated_at": "2016-06-16T10:27:19.000+01:00",
            "updated_by_name": "Seymour Butts 650",
            "created_by_name": "Seymour Butts 650"
          },
          {
            "id": 5,
            "patient_id": 820,
            "description": "this patient is a pest",
            "created_by_id": 651,
            "updated_by_id": 651,
            "created_at": "2016-06-16T10:27:19.000+01:00",
            "updated_at": "2016-06-16T10:27:19.000+01:00",
            "updated_by_name": "Seymour Butts 651",
            "created_by_name": "Seymour Butts 651"
          },
          {
            "id": 6,
            "patient_id": 820,
            "description": "this patient is a pest",
            "created_by_id": 652,
            "updated_by_id": 652,
            "created_at": "2016-06-16T10:27:19.000+01:00",
            "updated_at": "2016-06-16T10:27:19.000+01:00",
            "updated_by_name": "Seymour Butts 652",
            "created_by_name": "Seymour Butts 652"
          }
        ]

## Flags/{:patient_id} collection [/flags/{:patient_id}]

### Flags/{:patient_id} Index [GET]

+ Response 200 application/json

        [
          {
            "id": 7,
            "patient_id": 822,
            "description": "this patient is a pest",
            "created_by_id": 658,
            "updated_by_id": 658,
            "created_at": "2016-06-16T10:27:20.000+01:00",
            "updated_at": "2016-06-16T10:27:20.000+01:00",
            "updated_by_name": "Seymour Butts 658",
            "created_by_name": "Seymour Butts 658"
          },
          {
            "id": 8,
            "patient_id": 822,
            "description": "this patient is a pest",
            "created_by_id": 659,
            "updated_by_id": 659,
            "created_at": "2016-06-16T10:27:20.000+01:00",
            "updated_at": "2016-06-16T10:27:20.000+01:00",
            "updated_by_name": "Seymour Butts 659",
            "created_by_name": "Seymour Butts 659"
          },
          {
            "id": 9,
            "patient_id": 822,
            "description": "this patient is a pest",
            "created_by_id": 660,
            "updated_by_id": 660,
            "created_at": "2016-06-16T10:27:20.000+01:00",
            "updated_at": "2016-06-16T10:27:20.000+01:00",
            "updated_by_name": "Seymour Butts 660",
            "created_by_name": "Seymour Butts 660"
          }
        ]

## Flags/{:patient_id} collection [/flags/{:patient_id}]

### Flags/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "description": "this is a test"
        }

+ Response 201 application/json

        {
          "id": 10,
          "patient_id": 823,
          "description": "this is a test",
          "created_by_id": 661,
          "updated_by_id": 661,
          "created_at": "2016-06-16T10:27:20.669+01:00",
          "updated_at": "2016-06-16T10:27:20.669+01:00",
          "updated_by_name": "Seymour Butts 1",
          "created_by_name": "Seymour Butts 1"
        }

## Flags/{:patient_id} collection [/flags/{:patient_id}]

### Flags/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "description": "this is a test"
        }

+ Response 201 application/json

        {
          "id": 11,
          "patient_id": 824,
          "description": "this is a test",
          "created_by_id": 662,
          "updated_by_id": 662,
          "created_at": "2016-06-16T10:27:20.833+01:00",
          "updated_at": "2016-06-16T10:27:20.833+01:00",
          "updated_by_name": "Seymour Butts 1",
          "created_by_name": "Seymour Butts 1"
        }

## Flags/{:id} collection [/flags/{:id}]

### Flags/{:id} Show [GET]

+ Response 200 application/json

        {
          "id": 12,
          "patient_id": 825,
          "description": "This patient is a pest",
          "created_by_id": 664,
          "updated_by_id": 664,
          "created_at": "2016-06-16T10:27:21.000+01:00",
          "updated_at": "2016-06-16T10:27:21.000+01:00",
          "updated_by_name": "Seymour Butts 664",
          "created_by_name": "Seymour Butts 664"
        }

## Flags/{:id} collection [/flags/{:id}]

### Flags/{:id} Update [PATCH]

+ Request 

    + Body

        {
          "description": "changed desc"
        }

+ Response 200 application/json

        {
          "id": 13,
          "patient_id": 826,
          "description": "changed desc",
          "created_by_id": 666,
          "updated_by_id": 665,
          "created_at": "2016-06-16T10:27:21.000+01:00",
          "updated_at": "2016-06-16T10:27:21.285+01:00",
          "updated_by_name": "Seymour Butts 1",
          "created_by_name": "Seymour Butts 666"
        }

## Flags/{:id} collection [/flags/{:id}]

### Flags/{:id} Destroy [DELETE]

+ Response 200 application/json

        {
          "id": 14,
          "patient_id": 827,
          "description": "This patient is a pest",
          "created_by_id": 668,
          "updated_by_id": 668,
          "created_at": "2016-06-16T10:27:21.000+01:00",
          "updated_at": "2016-06-16T10:27:21.465+01:00",
          "updated_by_name": "Seymour Butts 668",
          "created_by_name": "Seymour Butts 668"
        }

# Redemptions/{:patient_id}

description blah blah blah

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "CORPSUB1543A",
          "redemption_type": "promotion"
        }

+ Response 200 application/json

        {
          "id": 52,
          "status": "Active",
          "code": "CORPSUB1543A",
          "promotion_name": "promotion_1",
          "activated_at": "2016-06-14T10:51:07.030+01:00",
          "promotion_type": "subscription",
          "plan_title": "Paid Plan 1401",
          "redemption_end_date": "2016-07-14",
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "CORPSUB1E428",
          "redemption_type": "promotion"
        }

+ Response 200 application/json

        {
          "id": 53,
          "status": "Active",
          "code": "CORPSUB1E428",
          "promotion_name": "promotion_1",
          "activated_at": "2016-06-14T10:51:07.974+01:00",
          "promotion_type": "subscription",
          "plan_title": "Paid Plan 1407",
          "redemption_end_date": "2016-07-14",
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "CORPSUB16105",
          "redemption_type": "promotion"
        }

+ Response 200 application/json

        {
          "id": 54,
          "status": "Active",
          "code": "CORPSUB16105",
          "promotion_name": "promotion_1",
          "activated_at": "2016-06-14T10:51:08.336+01:00",
          "promotion_type": "subscription",
          "plan_title": "Paid Plan 1409",
          "redemption_end_date": "2016-07-14",
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 56,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 57,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 58,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 59,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 60,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "regcode1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 61,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "REGCODE1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 62,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "regCode1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 63,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "CORPSUB16C69",
          "redemption_type": "hybrid"
        }

+ Response 200 application/json

        {
          "id": 64,
          "status": "Active",
          "code": "CORPSUB16C69",
          "promotion_name": "promotion_1",
          "activated_at": "2016-06-14T10:51:12.788+01:00",
          "promotion_type": "subscription",
          "plan_title": "Paid Plan 1443",
          "redemption_end_date": "2016-07-14",
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "CORPSUB1DF1E",
          "redemption_type": "hybrid"
        }

+ Response 200 application/json

        {
          "id": 65,
          "status": "Active",
          "code": "CORPSUB1DF1E",
          "promotion_name": "promotion_1",
          "activated_at": "2016-06-14T10:51:13.113+01:00",
          "promotion_type": "subscription",
          "plan_title": "Paid Plan 1445",
          "redemption_end_date": "2016-07-14",
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "hybrid"
        }

+ Response 200 application/json

        {
          "id": 66,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "hybrid"
        }

+ Response 200 application/json

        {
          "id": 67,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "hybrid"
        }

+ Response 200 application/json

        {
          "id": 68,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "CORPSUB1F9B0",
          "redemption_type": "promotion"
        }

+ Response 200 application/json

        {
          "id": 76,
          "status": "Active",
          "code": "CORPSUB1F9B0",
          "promotion_name": "promotion_1",
          "activated_at": "2016-06-14T10:51:16.817+01:00",
          "promotion_type": "subscription",
          "plan_title": "Paid Plan 1453",
          "redemption_end_date": "2016-06-15",
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "CORPSUB1F7F0",
          "redemption_type": "promotion"
        }

+ Response 200 application/json

        {
          "id": 77,
          "status": "Active",
          "code": "CORPSUB1F7F0",
          "promotion_name": "promotion_1",
          "activated_at": "2016-06-14T10:51:17.161+01:00",
          "promotion_type": "subscription",
          "plan_title": "Paid Plan 1455",
          "redemption_end_date": "2016-06-15",
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 78,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 79,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "CORPSUB197CC",
          "redemption_type": "promotion"
        }

+ Response 200 application/json

        {
          "id": 52,
          "status": "Active",
          "code": "CORPSUB197CC",
          "promotion_name": "promotion_1",
          "activated_at": "2016-06-14T11:02:28.472+01:00",
          "promotion_type": "subscription",
          "plan_title": "Paid Plan 1401",
          "redemption_end_date": "2016-07-14",
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "CORPSUB136EE",
          "redemption_type": "promotion"
        }

+ Response 200 application/json

        {
          "id": 53,
          "status": "Active",
          "code": "CORPSUB136EE",
          "promotion_name": "promotion_1",
          "activated_at": "2016-06-14T11:02:29.322+01:00",
          "promotion_type": "subscription",
          "plan_title": "Paid Plan 1407",
          "redemption_end_date": "2016-07-14",
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "CORPSUB1FBD7",
          "redemption_type": "promotion"
        }

+ Response 200 application/json

        {
          "id": 54,
          "status": "Active",
          "code": "CORPSUB1FBD7",
          "promotion_name": "promotion_1",
          "activated_at": "2016-06-14T11:02:29.711+01:00",
          "promotion_type": "subscription",
          "plan_title": "Paid Plan 1409",
          "redemption_end_date": "2016-07-14",
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 56,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 57,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 58,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 59,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 60,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "regcode1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 61,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "REGCODE1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 62,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "regCode1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 63,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "CORPSUB14815",
          "redemption_type": "hybrid"
        }

+ Response 200 application/json

        {
          "id": 64,
          "status": "Active",
          "code": "CORPSUB14815",
          "promotion_name": "promotion_1",
          "activated_at": "2016-06-14T11:02:33.787+01:00",
          "promotion_type": "subscription",
          "plan_title": "Paid Plan 1443",
          "redemption_end_date": "2016-07-14",
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "CORPSUB1DE86",
          "redemption_type": "hybrid"
        }

+ Response 200 application/json

        {
          "id": 65,
          "status": "Active",
          "code": "CORPSUB1DE86",
          "promotion_name": "promotion_1",
          "activated_at": "2016-06-14T11:02:34.136+01:00",
          "promotion_type": "subscription",
          "plan_title": "Paid Plan 1445",
          "redemption_end_date": "2016-07-14",
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "hybrid"
        }

+ Response 200 application/json

        {
          "id": 66,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "hybrid"
        }

+ Response 200 application/json

        {
          "id": 67,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "hybrid"
        }

+ Response 200 application/json

        {
          "id": 68,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "CORPSUB10020",
          "redemption_type": "promotion"
        }

+ Response 200 application/json

        {
          "id": 76,
          "status": "Active",
          "code": "CORPSUB10020",
          "promotion_name": "promotion_1",
          "activated_at": "2016-06-14T11:02:38.170+01:00",
          "promotion_type": "subscription",
          "plan_title": "Paid Plan 1453",
          "redemption_end_date": "2016-06-15",
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "CORPSUB17891",
          "redemption_type": "promotion"
        }

+ Response 200 application/json

        {
          "id": 77,
          "status": "Active",
          "code": "CORPSUB17891",
          "promotion_name": "promotion_1",
          "activated_at": "2016-06-14T11:02:38.551+01:00",
          "promotion_type": "subscription",
          "plan_title": "Paid Plan 1455",
          "redemption_end_date": "2016-06-15",
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 78,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 79,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "CORPSUB14FA4",
          "redemption_type": "promotion"
        }

+ Response 200 application/json

        {
          "id": 52,
          "status": "Active",
          "code": "CORPSUB14FA4",
          "promotion_name": "promotion_1",
          "activated_at": "2016-06-16T10:28:31.626+01:00",
          "promotion_type": "subscription",
          "plan_title": "Paid Plan 1463",
          "redemption_end_date": "2016-07-16",
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "CORPSUB150A6",
          "redemption_type": "promotion"
        }

+ Response 200 application/json

        {
          "id": 53,
          "status": "Active",
          "code": "CORPSUB150A6",
          "promotion_name": "promotion_1",
          "activated_at": "2016-06-16T10:28:32.622+01:00",
          "promotion_type": "subscription",
          "plan_title": "Paid Plan 1469",
          "redemption_end_date": "2016-07-16",
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "CORPSUB14EB4",
          "redemption_type": "promotion"
        }

+ Response 200 application/json

        {
          "id": 54,
          "status": "Active",
          "code": "CORPSUB14EB4",
          "promotion_name": "promotion_1",
          "activated_at": "2016-06-16T10:28:33.029+01:00",
          "promotion_type": "subscription",
          "plan_title": "Paid Plan 1471",
          "redemption_end_date": "2016-07-16",
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 56,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 57,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 58,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 59,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 60,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "regcode1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 61,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "REGCODE1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 62,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "regCode1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 63,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "CORPSUB17B90",
          "redemption_type": "hybrid"
        }

+ Response 200 application/json

        {
          "id": 64,
          "status": "Active",
          "code": "CORPSUB17B90",
          "promotion_name": "promotion_1",
          "activated_at": "2016-06-16T10:28:38.402+01:00",
          "promotion_type": "subscription",
          "plan_title": "Paid Plan 1505",
          "redemption_end_date": "2016-07-16",
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "CORPSUB18C78",
          "redemption_type": "hybrid"
        }

+ Response 200 application/json

        {
          "id": 65,
          "status": "Active",
          "code": "CORPSUB18C78",
          "promotion_name": "promotion_1",
          "activated_at": "2016-06-16T10:28:38.778+01:00",
          "promotion_type": "subscription",
          "plan_title": "Paid Plan 1507",
          "redemption_end_date": "2016-07-16",
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "hybrid"
        }

+ Response 200 application/json

        {
          "id": 66,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "hybrid"
        }

+ Response 200 application/json

        {
          "id": 67,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "hybrid"
        }

+ Response 200 application/json

        {
          "id": 68,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "CORPSUB130B4",
          "redemption_type": "promotion"
        }

+ Response 200 application/json

        {
          "id": 76,
          "status": "Active",
          "code": "CORPSUB130B4",
          "promotion_name": "promotion_1",
          "activated_at": "2016-06-16T10:28:43.344+01:00",
          "promotion_type": "subscription",
          "plan_title": "Paid Plan 1515",
          "redemption_end_date": "2016-06-17",
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "CORPSUB13D1F",
          "redemption_type": "promotion"
        }

+ Response 200 application/json

        {
          "id": 77,
          "status": "Active",
          "code": "CORPSUB13D1F",
          "promotion_name": "promotion_1",
          "activated_at": "2016-06-16T10:28:43.893+01:00",
          "promotion_type": "subscription",
          "plan_title": "Paid Plan 1517",
          "redemption_end_date": "2016-06-17",
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 78,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }

## Redemptions/{:patient_id} collection [/redemptions/{:patient_id}]

### Redemptions/{:patient_id} Create [POST]

+ Request 

    + Body

        {
          "code": "RegCode1",
          "redemption_type": "registration"
        }

+ Response 200 application/json

        {
          "id": 79,
          "status": "Inactive",
          "code": null,
          "promotion_name": null,
          "activated_at": null,
          "promotion_type": null,
          "plan_title": null,
          "redemption_end_date": null,
          "appointments_left": "N/A",
          "appointments_booked": "N/A",
          "is_reactivatable": false
        }
